### ISSUE TITLE
Error: Stream does not support seeking

### ISSUE THREAD

**Issue by joelamos** [filoe/cscore#114]
I'm trying to play an online radio station's stream via WasapiOut.play, but I get the below message about the stream not supporting seeking. Is this a limitation or a bug?

```
Unhandled Exception: System.NotSupportedException: Stream does not support seeking.
   at System.IO.BufferedStream.get_Position()
   at CSCore.Tags.ID3.ID3v2.SkipTag(Stream stream)
   at CSCore.Codecs.MP3.DmoMp3Decoder.ParseForMp3Frames(Stream stream, Boolean enableSeeking)
   at CSCore.Codecs.MP3.DmoMp3Decoder..ctor(Stream stream, Boolean enableSeeking)
   at CSCore.Codecs.MP3.Mp3WebStream.BufferProc(Object o)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by filoe** [comment]
Should be fixed. Can you confirm that?

**Comment by joelamos** [comment]
I am unsure, as I am using v 1.0 from NuGet, but here is a stream URL that gives the error: `http://nprdmp-live01-mp3.akacast.akamaistream.net/7/998/364916/v1/npr.akacast.akamaistream.net/nprdmp_live01_mp3`

**Comment by filoe** [comment]
I've did a few tests. It should work quite stable now. But to be honest, I currently have to not the time to test it more intense. Please try it out and give me some feedback :)
Thanks!
