### ISSUE TITLE
CoreAudioApiException when Initializing after using GetDefaultAudioEndpoint

### ISSUE THREAD

**Issue by cb-dtf** [filoe/cscore#203]
I've debugged this as far as I can without pulling the source.

My goal is to record a small sound file using the microphone, inside an existing WPF application.
There exists two active recording devices, one of them is both communication device and multimedia device. 
It is not chosen per default, so I'm trying to select it manually.

This is the (somewhat simple) code that should do the trick. 
`
WasapiLoopbackCapture wasapiCapture = new WasapiLoopbackCapture();
wasapiCapture.Device = new MMDeviceEnumerator().GetDefaultAudioEndpoint(DataFlow.Capture, Role.Communications);
wasapiCapture.Initialize();
`

But alas, no success.
Message: IAudioClient::Initialize caused an error: 0x88890003, "Unknown HRESULT".

Relevant stacktrace
<pre>
   at CSCore.SoundIn.WasapiCapture.InitializeInternal()
   at CSCore.SoundIn.WasapiCapture.Initialize()
</pre>

Bonus info: The device property of WasapiLoopbackCapture is set correctly, it is the initialization that seems to have a problem here.

I've taken a peak at the source, no dice I'm afraid.

**Comment by cb-dtf** [comment]
Darn it.

Figured out what went wrong, I built my code from the example in  cscore/Samples/RecordToWma/Program.cs
This uses the WasapiLoopbackCapture, but in my case that didn't work.


Don't think this is a bug then, but a clarification in the sample would be nice.
:)

**Comment by filoe** [comment]
Glad to hear that. I ll take a look at the sample.

**Comment by filoe** [comment]
I'm sorry for coming back to this so late.
What should be clarified?
