### ISSUE TITLE
NullReference exception at CSCore.SoundOut.WasapiOut.Finalize()

### ISSUE THREAD

**Issue by Ryogo-Z** [filoe/cscore#233]
Not doing anything unusual, just creating new WasapiOut and disposing old one. May be a threading issue, can't check by myself currently.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallbackNative(IMMNotificationClient notificationClient)
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(IMMNotificationClient notificationClient)
   at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
   at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean streamSwitch)
   at CSCore.SoundOut.WasapiOut.Dispose(Boolean disposing)
   at CSCore.SoundOut.WasapiOut.Finalize()`

**Comment by filoe** [comment]
What version are you using?

**Comment by Ryogo-Z** [comment]
1.2.1.1 from nuget.

**Comment by filoe** [comment]
Do you got some code the reproduce it?

**Comment by Ryogo-Z** [comment]
No, sorry. I could not reproduce it either - ended up just wrapping TerminateStreamRouting internal in try-catch.

**Comment by JJtheJJpro** [comment]
I'm having the same problem.

**Comment by filoe** [comment]
Please test whether this fixes your issue.

**Comment by JJtheJJpro** [comment]
HEY!!  It worked!  Thanks!

**Comment by filoe** [comment]
Glad to hear that.

**Comment by snalesso** [comment]
@filoe I stumbled on this issue today, lost 2 hours then tried compiling current repo's version (ahead of the the Nuget 1.2.1.1) and it seems to work.

I think it would be good to publish a new version on Nuget, since a quick look at the commit says there were other fixes to core classes.
