### ISSUE TITLE
Exception when changing system master volume on Windows 10

### ISSUE THREAD

**Issue by aleh4d** [filoe/cscore#310]
Exception when changing system master volume on Windows 10
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallbackNative(CSCore.CoreAudioAPI.IMMNotificationClient)
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.UnregisterEndpointNotificationCallback(CSCore.CoreAudioAPI.IMMNotificationClient)
   at CSCore.SoundOut.WasapiOut.TerminateStreamRouting()
   at CSCore.SoundOut.WasapiOut.CleanupResources(Boolean)
   at CSCore.SoundOut.WasapiOut.Dispose(Boolean)
   at CSCore.SoundOut.WasapiOut.Finalize()

**Comment by filoe** [comment]
Are you using the latest version of cscore?

**Comment by aleh4d** [comment]
Updated the version
it seems to work

**Comment by filoe** [comment]
Thanks, I'll close this.
