### ISSUE TITLE
CSCore.FFMPeg relies on Media Foundation

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#330]
I'm using CSCore.FFMpeg to play audio in Dopamine. A user notified inability to playback mp3's on Windows 10 Enterprise N 2016 LTSB (which is a Windows 10 edition without Media Foundation).
I expected CSCore.FFMpeg to play mp3's fine, as it is not using MediaFoundation decoder.
Please correct me if I'm wrong. Is CSCore.FFMpeg supposed to be able to play audio without Media Foundation or not? (This is more a question than a bug report) 

This is the stack trace when trying to play a mp3 file, using FFMpegDecoder on Windows 10 Enterprise N 2016 LTSB:

> Shuffle=False. Exception: Retrieving the COM class factory for component with CLSID {F447B69E-1884-4A7E-8055-346F74D6EDB3} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).. StackTrace:    at CSCore.DMO.WMResampler..ctor()
>    at CSCore.DSP.DmoResampler.Initialize(WaveFormat inputformat, WaveFormat outputformat)
>    at CSCore.DSP.DmoResampler..ctor(IWaveSource source, WaveFormat outputFormat, Boolean ignoreBaseStreamPosition)
>    at CSCore.SoundOut.WasapiOut.SetupWaveFormat(IWaveSource source, AudioClient audioClient)
>    at CSCore.SoundOut.WasapiOut.InitializeInternal()
>    at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
>    at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource) in C:\Users\rapha\Source\Repos\Dopamine\Dopamine.Core\Audio\CSCorePlayer.cs:line 360
>    at Dopamine.Core.Audio.CSCorePlayer.Play(String filename) in C:\Users\rapha\Source\Repos\Dopamine\Dopamine.Core\Audio\CSCorePlayer.cs:line 235
>    at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, MMDevice outputDevice) in C:\Users\rapha\Source\Repos\Dopamine\Dopamine.Core\Audio\CSCorePlayer.cs:line 243
>    at Dopamine.Services.Playback.PlaybackService.<>c__DisplayClass190_0.<StartPlaybackAsync>b__0() in C:\Users\rapha\Source\Repos\Dopamine\Dopamine.Services\Playback\PlaybackService.cs:line 1115
>    at System.Threading.Tasks.Task.Execute()

**Comment by digimezzo** [comment]
Ok, this is obviously caused because I'm using WasapiOut, which calls the DmoResampler(...) constructor in SetupWaveFormat(...). The DmoResampler constructor in turn calls WMResampler constructor which tries to access a COM interface which is not available on that edition of Windows.

Apparently, using DirectsoundOut on such crippled Windows edition, works.

**Comment by filoe** [comment]
Sorry for the late response. Was injured ...
Yes, you're right. The DmoResampler is used the resample the audio stream to the target samplerate.
It would be an option to use a native c# resampler which is currently not supported.
Do you have any troubles with it?

**Comment by digimezzo** [comment]
Hi @filoe, no problem. I hope you are well now.
I was trying to make my audio player compatible with Windows editions which don't have the Media Feature Pack installed, the so called N Editions (mostly because users don't know they have such edition, and assume that my player is broken). 
I assumed that FFmpegDecoder would allow audio playback on such editions. However, when combined with WasapiOut, I bump into the DmoResampler usage. When combined with DirectSoundOut, it works on Windows N Editions.  So that's a nice workaround. I use DIrectSoundOut as fallback mechanism when Media Foundation is not found.
