### ISSUE TITLE
The type initializer for 'CSCore.Codecs.CodecFactory' threw an exception

### ISSUE THREAD

**Issue by wealstarr** [filoe/cscore#338]
Hello,

Dopamine Music Player gives me this error when I try to play a song. Below is the Log-

> 2018-03-25 01:33:47.181|Error|PlaybackService.TryPlayAsync|Could not play the file C:\Users\Faudel\Desktop\Abou Debeing\Abou_Debeing-Debeinguerie-FR-2017-SO\02-abou_debeing-tacatwa.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: The type initializer for 'CSCore.Codecs.CodecFactory' threw an exception.. StackTrace:    at Dopamine.Common.Audio.CSCorePlayer..ctor()
   at Dopamine.Common.Audio.CSCorePlayer.get_Instance()
   at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

What's the cause of this issue and more importantly how can it be resolved ?

Any help will be greatly appreciated.

Thank you for reading.

**Comment by filoe** [comment]
Can you provide the file causing the crash?
