### ISSUE TITLE
MediaFoundationEncoder exception in Dispose method

### ISSUE THREAD

**Issue by mguillau42** [filoe/cscore#385]
Hi,

I am creating a simple C# program using CSCore in order to record the input of a microphone. I am testing my program in a Virtual Machine, when my host's microphone is set to pass it's input to the guest machine I am able to record to an MP3 (via MediaFoundationEncoder.CreateMP3Encoder) and later on Dispose said encoder, everything works fine.
However when the host's microphone is not set to pass it's input to the guest machine, I am unable to call Dispose on the encoder and the following exception occurs.
 
```
Unhandled exception: CSCore.MediaFoundation.MediaFoundationException (0xC00D4A44): IMFSinkWriter::GetStatistics caused an error: 0xc00d4a44, "The operation failed because no samples were processed by the sink.".
   at CSCore.MediaFoundation.MFSinkWriter.GetStatistics(Int32 streamIndex)
   at CSCore.MediaFoundation.MediaFoundationEncoder.Dispose(Boolean disposing)
   at CSCore.MediaFoundation.MediaFoundationEncoder.Dispose()
```
The problem seems to appear here: https://github.com/filoe/cscore/blob/master/CSCore/MediaFoundation/MediaFoundationEncoder.cs#L245

I tried catching this exception when calling the Dispose method in my program, however this means that I am unable to correctly Dispose of the sinkWriter, targetStream and targetBaseStream.

Should this be handled directly in the Dispose method ?

**Comment by mguillau42** [comment]
For information, I found a way of handling this in my program by creating the MediaFoundationEncoder only once data is available.
