### ISSUE TITLE
DirectSoundOut throws NullReferenceException on Finalize()

### ISSUE THREAD

**Issue by amysgames** [filoe/cscore#395]
As stated in the title, DirectSoundOut seems to be throwing a NullReferenceException if it's been initialized before closing the app. No exceptions if it hasn't been initialized yet. It seems to be a DirectSound issue specifically, because I switched to Wasapi and it didn't throw any exceptions. I'm using v1.2.1.2 from NuGet.

Here's the error I got:
> System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CSCore
  StackTrace:
   at CSCore.DirectSound.DirectSoundBuffer.StopNative()
   at CSCore.DirectSound.DirectSoundBuffer.Stop()
   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
   at CSCore.SoundOut.DirectSoundOut.Finalize()

**Comment by jbarber3388** [comment]
This is also an issue with the WaveIn and WaveInBuffer class as well.

#393

**Comment by filoe** [comment]
For a quick fix, try to use WasapiOut. #393.
