### ISSUE TITLE
Some MP3's which used to play, now throw "Could not find a supported format" CSCore.SoundOut.WasapiOut.SetupWaveFormat

### ISSUE THREAD

**Issue by rgodart** [filoe/cscore#63]
I updated cscore in my music player to the latest code from cscore-master. A user of my music player complains that MP3 files which used to work, don't play anymore. I've shared 2 of the files here (in the folder "Unplayable"): https://www.dropbox.com/sh/wr36rjx0u1u2aeo/AADnfLBQZ2oJXEIgWyRQHSOZa?dl=0

The cscore.dll with which the files did work in the past is also in that folder. As far as I could debug, it seems that now a "Could not find a supported format" exception is thrown in CSCore.SoundOut.WasapiOut.SetupWaveFormat. I couldn't find the changeset which caused this.

This is the stacktrace:

   at CSCore.SoundOut.WasapiOut.SetupWaveFormat(IWaveSource source, AudioClient audioClient)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut() in D:\Workspaces\VSOnline\Dopamine\Dev\Dopamine\Dopamine.Core\Audio\CSCorePlayer.vb:line 110
   at Dopamine.Core.Audio.CSCorePlayer._Closure$__32-0._Lambda$__0() in D:\Workspaces\VSOnline\Dopamine\Dev\Dopamine\Dopamine.Core\Audio\CSCorePlayer.vb:line 247
   at System.Threading.Tasks.Task.Execute()

**Comment by filoe** [comment]
I'm sorry for the late response. This should fix the bug. Wasn't expecting multiple id3v2 tags at the beginning of a file.

**Comment by rgodart** [comment]
Thanks! That fixes it.
