### ISSUE TITLE
Sound source over https

### ISSUE THREAD

**Issue by joelamos** [filoe/cscore#89]
Is there a way to get an IWaveSource over HTTPS?

**Comment by filoe** [comment]
You can try to use the the `CodecFactory.Instance.GetCodec` method by passing an uri object, containing the https url.

**Comment by joelamos** [comment]
Yes that seems to work with some sources over HTTPS. However, when I try to use a YouTube stream URL, I get an error. Here's the error log:

```
System.NotSupportedException was unhandled
  HResult=-2146233067
  Message=Codec not supported.
  Source=CSCore
  StackTrace:
       at CSCore.Codecs.CodecFactory.GetCodec(Uri uri)
       at AudioTest.Program.GetSoundSource(String path) in C:\Users\Joel Christophel\documents\visual studio 2015\Projects\ConsoleApplication6\ConsoleApplication6\Program.cs:line 72
       at AudioTest.Program.Main(String[] args) in C:\Users\Joel Christophel\documents\visual studio 2015\Projects\ConsoleApplication6\ConsoleApplication6\Program.cs:line 32
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       ErrorCode=-2147024891
       HResult=-2147024891
       InterfaceName=Interops
       Member=MFCreateSourceReaderFromURL
       Message=Interops::MFCreateSourceReaderFromURL caused an error: 0x80070005, "Access is denied.".
       Source=CSCore
       StackTrace:
            at CSCore.MediaFoundation.MediaFoundationCore.CreateSourceReaderFromUrl(String url)
            at CSCore.MediaFoundation.MediaFoundationDecoder..ctor(String uri)
            at CSCore.Codecs.CodecFactory.GetCodec(Uri uri)
       InnerException:
```

Here's an example of a URL I'm using:
https://r5---sn-vgqsenls.googlevideo.com/videoplayback?ip=184.16.196.9&ms=au&mt=1462469441&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=us&id=o-APm9w1jClw4qoB2GxtFpg91v7Bchr6TYUh7HvUsf4dN4&keepalive=yes&mm=31&mn=sn-vgqsenls&clen=3651834&initcwndbps=263750&pcm2=yes&requiressl=yes&mime=audio%2Fwebm&gir=yes&key=yt6&nh=IgpwcjA0Lm9yZDEyKgkxMjcuMC4wLjE&fexp=9405185%2C9407157%2C9416126%2C9416891%2C9417580%2C9417827%2C9422596%2C9424135%2C9428398%2C9429854%2C9431012%2C9432683%2C9433096%2C9433946%2C9434344%2C9434390%2C9434811%2C9435505%2C9435849%2C9435948&lmt=1449639772528871&sver=3&ipbits=0&dur=224.161&mv=m&expire=1462491254&upn=LIm38OENoj8&source=youtube&pl=14&itag=251&signature=092E06883138D2DF816378FF1058D32F533A1B3F.A68BE33324FB6A450C232A7F4DF767DE0366E5&ratebypass=yes
